/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package botlab.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class bot_status_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public double xyt[];
    public double cov[][];
 
    public bot_status_t()
    {
        xyt = new double[3];
        cov = new double[3][3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xb3bea18f4e5562c0L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(botlab.lcmtypes.bot_status_t.class))
            return 0L;
 
        classes.add(botlab.lcmtypes.bot_status_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.xyt[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeDouble(this.cov[a][b]); 
            }
        }
 
    }
 
    public bot_status_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public bot_status_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static botlab.lcmtypes.bot_status_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        botlab.lcmtypes.bot_status_t o = new botlab.lcmtypes.bot_status_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.xyt = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.xyt[a] = ins.readDouble();
        }
 
        this.cov = new double[(int) 3][(int) 3];
        for (int a = 0; a < 3; a++) {
            for (int b = 0; b < 3; b++) {
                this.cov[a][b] = ins.readDouble();
            }
        }
 
    }
 
    public botlab.lcmtypes.bot_status_t copy()
    {
        botlab.lcmtypes.bot_status_t outobj = new botlab.lcmtypes.bot_status_t();
        outobj.utime = this.utime;
 
        outobj.xyt = new double[(int) 3];
        System.arraycopy(this.xyt, 0, outobj.xyt, 0, 3); 
        outobj.cov = new double[(int) 3][(int) 3];
        for (int a = 0; a < 3; a++) {
            System.arraycopy(this.cov[a], 0, outobj.cov[a], 0, 3);        }
 
        return outobj;
    }
 
}

