/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package botlab.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class diff_drive_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public float left;
    public boolean left_enabled;
    public float right;
    public boolean right_enabled;
 
    public diff_drive_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xf5f59869ca7f7ca8L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(botlab.lcmtypes.diff_drive_t.class))
            return 0L;
 
        classes.add(botlab.lcmtypes.diff_drive_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeFloat(this.left); 
 
        outs.writeByte( this.left_enabled ? 1 : 0); 
 
        outs.writeFloat(this.right); 
 
        outs.writeByte( this.right_enabled ? 1 : 0); 
 
    }
 
    public diff_drive_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public diff_drive_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static botlab.lcmtypes.diff_drive_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        botlab.lcmtypes.diff_drive_t o = new botlab.lcmtypes.diff_drive_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.left = ins.readFloat();
 
        this.left_enabled = ins.readByte()!=0;
 
        this.right = ins.readFloat();
 
        this.right_enabled = ins.readByte()!=0;
 
    }
 
    public botlab.lcmtypes.diff_drive_t copy()
    {
        botlab.lcmtypes.diff_drive_t outobj = new botlab.lcmtypes.diff_drive_t();
        outobj.utime = this.utime;
 
        outobj.left = this.left;
 
        outobj.left_enabled = this.left_enabled;
 
        outobj.right = this.right;
 
        outobj.right_enabled = this.right_enabled;
 
        return outobj;
    }
 
}

